name: Build Check

on:
  push:
    branches: [ master, develop ]
    paths: 'src/**'
  pull_request:
    branches: [ master, develop ]
    paths: 'src/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Run build
      run: dotnet publish src/KyoshinEewViewer/KyoshinEewViewer.csproj -c Debug -o out
    - name: Archive artifact
      uses: actions/upload-artifact@v1
      with:
        name: KyoshinEewViewer for ingen
        path: out
