name: Build Check

on:
  push:
    branches: [ master, develop ]
    paths: 'src/**'
  pull_request:
    branches: [ master, develop ]
    paths: 'src/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore tools
      run: dotnet tool restore
    - name: Run build script
      run: dotnet script build_dev.csx
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: KyoshinEewViewer.exe
        path: out/KyoshinEewViewer.exe
